services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - BASE_URL=${MEALIE_BASE_URL} # Important for reverse proxy
      - DB_ENGINE=${MEALIE_DB_ENGINE}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SECRET_KEY=${MEALIE_SECRET_KEY}
      - VIRTUAL_HOST=${MEALIE_DOMAIN}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_FROM_NAME=${MEALIE_SMTP_FROM_NAME}
      - SMTP_AUTH_STRATEGY=${MEALIE_SMTP_AUTH_STRATEGY}
      - SMTP_FROM_EMAIL=${SMTP_FROM}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    volumes:
      - /opt/docker/mealie/data:/app/data

    ports:
      - 9925:9000 # Expose Mealie's port (internal)
    networks:
      - shared_db
      - shared_proxy
networks:
  shared_db:
    external: true
  shared_proxy:
    external: true
