services:

  dashdot:
    container_name: ${COMPOSE_PROJECT_NAME}-dashdot
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true # Required by Dashdot for host system stats
    security_opt:
      - no-new-privileges:true
    environment:
      - VIRTUAL_HOST=${DASHDOT_HOST}
      - VIRTUAL_PORT=3001
      - DASHDOT_ENABLE_CPU_TEMPS=${DASHDOT_ENABLE_CPU_TEMPS}
    volumes:
      - /proc/1/ns/net:/mnt/host_ns_net:ro
      - /etc/os-release:/etc/os-release:ro
      - /:/mnt/host:ro
    networks:
      - shared_proxy
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  uptime-kuma:
    container_name: ${COMPOSE_PROJECT_NAME}-kuma
    image: louislam/uptime-kuma:2
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - VIRTUAL_HOST=${KUMA_HOST}
      - VIRTUAL_PORT=3001
    volumes:
      - ${KUMA_BASE_PATH}:/app/data:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - shared_proxy

  grafana:
    container_name: ${COMPOSE_PROJECT_NAME}-grafana
    image: grafana/grafana-enterprise:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "472:472" # Replaced root (user: 0) with default Grafana unprivileged UID/GID
    environment:
      - TZ=${TZ}
      - VIRTUAL_HOST=${GRAFANA_HOST}
      - VIRTUAL_PORT=3000
    volumes:
      - ${GRAFANA_BASE_PATH}/data:/var/lib/grafana
      - ${GRAFANA_BASE_PATH}/logs:/var/log/grafana
    networks:
      - shared_proxy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

networks:
  shared_proxy:
    external: true
