services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: always
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VIRTUAL_HOST=sonarr.meine-domain.de
    volumes:
      - /opt/docker/sonarr:/config
      - /mnt/media/video/tv:/tv
      - /opt/downloads/completed:/downloads
    networks:
      - shared_proxy
  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr
    restart: always
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VIRTUAL_HOST=lidarr.meine-domain.de
    volumes:
      - /opt/docker/lidarr:/config
      - /mnt/media/music/lidarr:/music
      - /opt/downloads/completed:/downloads
    networks:
      - shared_proxy
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: always
    environment:
      - HOME=/root
      - TERM=xterm
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VIRTUAL_HOST=bazarr.meine-domain.de
    volumes:
      - /mnt/media/video/tv:/tv:rw
      - /mnt/media/video/movies:/movies:rw
      - /opt/docker/bazarr:/config:rw
    networks:
      - shared_proxy
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: always
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/root
      - LANGUAGE=en_US.UTF-8
      - LANG=en_US.UTF-8
      - TERM=xterm
      - XDG_CONFIG_HOME=/config/xdg
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VIRTUAL_HOST=radarr.meine-domain.de
    volumes:
      - /opt/docker/radarr:/config:rw
      - /opt/downloads/completed:/downloads:rw
      - /mnt/media/video/movies:/movies:rw
    networks:
      - shared_proxy
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: always
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VIRTUAL_HOST=prowlarr.meine-domain.de
    volumes:
      - /opt/docker/prowlarr:/config
    networks:
      - shared_proxy
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd:latest
    restart: always
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VIRTUAL_HOST=sabnzb.meine-domain.de
    volumes:
      - /opt/docker/sabnzbd:/config
      - /opt/downloads/completed:/downloads #optional
      - /opt/downloads/intermediate:/incomplete-downloads #optional
    networks:
      - shared_proxy
  overseerr:
    container_name: overseerr
    image: ghcr.io/seerr-team/seerr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VIRTUAL_HOST=overseerr.meine-domain.de
    volumes:
      - /opt/docker/overseerr:/app/config # Contains all relevant configuration files.

    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    networks:
      - shared_proxy
    init: true
networks:
  shared_proxy:
    external: true
