services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VIRTUAL_HOST=${HOMEPAGE_DOMAIN}
      - VIRTUAL_PORT=${HOMEPAGE_PORT}
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
    volumes:
      - /opt/docker/homepage:/app/config # All your .yaml files will live here
      - /var/run/docker.sock:/var/run/docker.sock:ro # Read-only access to monitor other containers
    networks:
      - shared_proxy

  5etools:
    container_name: 5etools
    image: jafner/5etools-docker
    restart: unless-stopped
    environment:
      #- IMG=TRUE # Set to TRUE to pull images from https://github.com/5etools-mirror-2/5etools-img (as a Git submodule)
      - OFFLINE_MODE=${FIVETOOLS_OFFLINE_MODE} # Optional. Expects "TRUE" or "FALSE". Disables checking for new updates.
      - TZ=${TZ}
      - VIRTUAL_HOST=${FIVETOOLS_DOMAIN}
    volumes:
      - /opt/docker/5etools:/usr/local/apache2/htdocs
    networks:
      - shared_proxy

networks:
  shared_proxy:
    external: true
