services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:16
    container_name: forgejo
    restart: unless-stopped
    networks:
      - forgejo_net
      - shared_proxy
    ports:
      - "222:22"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=sqlite3
      - FORGEJO__server__DOMAIN=git.islasorna.de
      - FORGEJO__server__ROOT_URL=https://git.islasorna.de
      - FORGEJO__actions__ENABLED=true
      - FORGEJO__service__DISABLE_REGISTRATION=true
      - FORGEJO__server__LOCAL_ROOT_URL=http://forgejo:3000
      - VIRTUAL_HOST=git.islasorna.de
      - VIRTUAL_PORT=3000
      - FORGEJO__server__SSH_PORT=222         # The port displayed in the Web UI
      - FORGEJO__server__SSH_LISTEN_PORT=22   #
    volumes:
      - /opt/docker/forgejo/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  forgejo-runner:
    image: code.forgejo.org/forgejo/runner:13
    container_name: forgejo-runner
    user: "1000:999"
    restart: unless-stopped
    networks:
      - forgejo_net
    environment:
      - FORGEJO_INSTANCE_URL=http://forgejo:3000
      - FORGEJO_RUNNER_REGISTRATION_TOKEN=${FORGEJO_TOKEN}
      - FORGEJO_RUNNER_NAME=docker-runner
      - FORGEJO_RUNNER_LABELS=docker:docker://node:20,ubuntu-latest:docker://node:20
    volumes:
      - /opt/docker/forgejo/runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - forgejo
    command: forgejo-runner daemon


networks:
  forgejo_net:
  shared_proxy:
    external: true