services:
  forgejo:
    container_name: forgejo
    image: codeberg.org/forgejo/forgejo:16
    restart: unless-stopped
    environment:
      - USER_UID=${PUID}
      - USER_GID=${PGID}
      - FORGEJO__database__DB_TYPE=${FORGEJO_DB_TYPE}
      - FORGEJO__server__DOMAIN=${FORGEJO_DOMAIN}
      - FORGEJO__server__ROOT_URL=${FORGEJO_ROOT_URL}
      - FORGEJO__actions__ENABLED=${FORGEJO_ACTIONS_ENABLED}
      - FORGEJO__service__DISABLE_REGISTRATION=${FORGEJO_DISABLE_REGISTRATION}
      - FORGEJO__server__LOCAL_ROOT_URL=${FORGEJO_LOCAL_ROOT_URL}
      - VIRTUAL_HOST=${FORGEJO_DOMAIN}
      - VIRTUAL_PORT=${FORGEJO_PORT}
      - FORGEJO__server__SSH_PORT=${FORGEJO_SSH_PORT}         # The port displayed in the Web UI
      - FORGEJO__server__SSH_LISTEN_PORT=${FORGEJO_SSH_LISTEN_PORT}   #
    volumes:
      - /opt/docker/forgejo/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    ports:
      - "222:22"
    networks:
      - forgejo_net
      - shared_proxy
  forgejo-runner:
    container_name: forgejo-runner
    image: code.forgejo.org/forgejo/runner:13
    command: forgejo-runner daemon


    restart: unless-stopped
    depends_on:
      - forgejo
    user: "1000:999"
    environment:
      - FORGEJO_INSTANCE_URL=http://forgejo:3000
      - FORGEJO_RUNNER_REGISTRATION_TOKEN=${FORGEJO_TOKEN}
      - FORGEJO_RUNNER_NAME=${FORGEJO_RUNNER_NAME}
      - FORGEJO_RUNNER_LABELS=${FORGEJO_RUNNER_LABELS}
    volumes:
      - /opt/docker/forgejo/runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - forgejo_net
networks:
  forgejo_net:
  shared_proxy:
    external: true
