services:

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    network_mode: host
    privileged: false
    security_opt:
      - apparmor:unconfined
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VIRTUAL_HOST=${HASS_DOMAIN}
      - VIRTUAL_PORT=${HASS_PORT}
    volumes:
      - /opt/docker/homeassistant:/config
      - /run/dbus:/run/dbus:ro
      - /var/run/dbus:/var/run/dbus:ro
    devices:
      - /dev/weatherstick:/dev/weatherstick
      - /dev/bus/usb/003/002:/dev/bus/usb/003/002
      - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2121030-if00:/dev/ttyACM0

    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    group_add:
      - "20" # Matched to your host dialout GID
  music-assistant:
    container_name: music-assistant
    image: ghcr.io/music-assistant/server:stable
    restart: unless-stopped
    network_mode: host
    privileged: false
    environment:
      - TZ=${TZ}
      - VIRTUAL_HOST=${MASS_DOMAIN}
      - VIRTUAL_PORT=${MASS_PORT}
    volumes:
      - /opt/docker/music-assistant:/data
      - /mnt/media/music/lidarr/:/media:ro

    cap_add:
      - DAC_READ_SEARCH
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    privileged: false
    environment:
      - TZ=${TZ}
    volumes:
      - /opt/docker/mosquitto/config:/mosquitto/config
      - /opt/docker/mosquitto/log:/mosquitto/log
      - /opt/docker/mosquitto/data:/mosquitto/data

    ports:
      - "1883:1883" # Exposes MQTT to local LAN (Valetudo) & Host (Home Assistant)
      - "9001:9001" # WebSockets (Optional)
  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    restart: unless-stopped
    network_mode: host
    privileged: false
    security_opt:
      - apparmor:unconfined
    environment:
      - TZ=${TZ}
    volumes:
      - /opt/docker/python-matter-server/data:/data
      - /run/dbus:/run/dbus:ro
