version: '3.8'

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    volumes:
      - /opt/docker/homepage:/app/config # All your .yaml files will live here
      - /var/run/docker.sock:/var/run/docker.sock:ro # Read-only access to monitor other containers
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VIRTUAL_HOST=homepage.islasorna.de
      - VIRTUAL_PORT=3000
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
    networks:
      - shared_proxy

networks:
  shared_proxy:
    external: true