services:
  codex:
    container_name: codex
    image: docker.io/ajslater/codex
    restart: on-failure
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VIRTUAL_PORT=9810
      - VIRTUAL_HOST=codex.meine-domain.de
    volumes:
      - /opt/docker/codex/config:/config
      - /mnt/media/library/comics:/comics:ro
    networks:
      - shared_proxy

networks:
  shared_proxy:
    external: true
