
services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: ${COMPOSE_PROJECT_NAME}-tdarr
    restart: always
    networks:
      - shared_proxy
    devices:
      - ${TDARR_DRI_DEVICE}:${TDARR_DRI_DEVICE}
    ports:
      - "${TDARR_WEBUI_PORT}:${TDARR_WEBUI_PORT}"
      - "${TDARR_SERVER_PORT}:${TDARR_SERVER_PORT}"
      - "${TDARR_INTERNAL_NODE_PORT}:${TDARR_INTERNAL_NODE_PORT}"
      - "${TDARR_EXTRA_NODE_PORT}:${TDARR_EXTRA_NODE_PORT}"
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      UMASK_SET: ${UMASK}
      serverIP: ${TDARR_SERVER_IP}
      serverPort: ${TDARR_SERVER_PORT}
      webUIPort: ${TDARR_WEBUI_PORT}
      internalNode: ${TDARR_INTERNAL_NODE}
      inContainer: ${TDARR_IN_CONTAINER}
      nodeName: ${TDARR_NODE_NAME}
      # --- nginx proxy environment ---
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${TDARR_WEBUI_PORT}

    volumes:
      - ${TDARR_BASE}/server:/app/server
      - ${TDARR_BASE}/configs:/app/configs
      - ${TDARR_BASE}/logs:/app/logs
      - ${MEDIA_PATH}:/media
      - ${TDARR_TEMP}:/temp

networks:
  shared_proxy:
    external: true