services:
  plex:
    container_name: plex
    image: linuxserver/plex:latest
    restart: always
    network_mode: host
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=${PLEX_VERSION}
      - VIRTUAL_HOST=${PLEX_DOMAIN}
      - VIRTUAL_PORT=${PLEX_PORT}
      - NETWORK_ACCESS=${PLEX_NETWORK_ACCESS}
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - /opt/docker/plex/conf:/config
      - /mnt/media/video/tv:/tv
      - /mnt/media/video/movies:/movies
      - /mnt/media/video/fitness:/fitness
      - /mnt/media/video/youtube:/youtube
      - /mnt/media/video/learning:/learning
      - /mnt/media/music/lidarr:/music
      - /mnt/media/audiobooks/audiobooks:/audiobooks
    devices:
      - /dev/dri:/dev/dri
  tautulli:
    container_name: tautulli
    image: tautulli/tautulli:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VIRTUAL_HOST=${TAUTULLI_DOMAIN}
    volumes:
      - /opt/docker/tautulli:/config:rw
    networks:
      - shared_proxy
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VIRTUAL_HOST=${AUDIOBOOKSHELF_DOMAIN}
    volumes:
      - /mnt/media/audiobooks/audiobooks:/audiobooks
      - /mnt/media/audiobooks/podcasts:/podcasts
      - /opt/docker/audiobookshelf/config:/config
      - /opt/docker/audiobookshelf/metadata:/metadata
    ports:
      - 13378:80
    networks:
      - shared_proxy
  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VIRTUAL_HOST=${METUBE_DOMAIN}
    volumes:
      - /mnt/media/video/youtube:/downloads
    networks:
      - shared_proxy
  calibre-web:
    container_name: calibre-web
    image: lscr.io/linuxserver/calibre-web:latest
    restart: unless-stopped


    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DOCKER_MODS=${CALIBRE_WEB_DOCKER_MODS} #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=${CALIBRE_WEB_OAUTHLIB_RELAX_TOKEN_SCOPE} #optional
      - VIRTUAL_HOST=${CALIBRE_WEB_DOMAIN}
    volumes:
      - /opt/docker/calibre-web:/config
      - /mnt/media/library/calibre:/books
    networks:
      - shared_proxy

  codex:
    container_name: codex
    image: docker.io/ajslater/codex
    restart: on-failure
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VIRTUAL_PORT=${CODEX_PORT}
      - VIRTUAL_HOST=${CODEX_DOMAIN}
    volumes:
      - /opt/docker/codex/config:/config
      - /mnt/media/library/comics:/comics:ro
    networks:
      - shared_proxy

  tdarr:
    container_name: tdarr-tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: always
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      UMASK_SET: ${UMASK}
      serverIP: ${TDARR_SERVER_IP}
      serverPort: ${TDARR_SERVER_PORT}
      webUIPort: ${TDARR_WEBUI_PORT}
      internalNode: ${TDARR_INTERNAL_NODE}
      inContainer: ${TDARR_IN_CONTAINER}
      nodeName: ${TDARR_NODE_NAME}
      # --- nginx proxy environment ---
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${TDARR_WEBUI_PORT}

    volumes:
      - ${TDARR_BASE}/server:/app/server
      - ${TDARR_BASE}/configs:/app/configs
      - ${TDARR_BASE}/logs:/app/logs
      - ${MEDIA_PATH}:/media
      - ${TDARR_TEMP}:/temp

    devices:
      - ${TDARR_DRI_DEVICE}:${TDARR_DRI_DEVICE}
    ports:
      - "${TDARR_WEBUI_PORT}:${TDARR_WEBUI_PORT}"
      - "${TDARR_SERVER_PORT}:${TDARR_SERVER_PORT}"
      - "${TDARR_INTERNAL_NODE_PORT}:${TDARR_INTERNAL_NODE_PORT}"
      - "${TDARR_EXTRA_NODE_PORT}:${TDARR_EXTRA_NODE_PORT}"
    networks:
      - shared_proxy

networks:
  shared_proxy:
    external: true
